import "./globals.css";

export const metadata = {
    title: "Crowdfunding Project Page",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com"></link>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
                <link href="https://fonts.googleapis.com/css2?family=Commissioner:wght@100..900&display=swap" rel="stylesheet"></link>
                <link rel="icon" href="favicon-32x32.png"></link>
            </head>
            <body className="bg-[#fafafa] font-[Commissioner]">{children}</body>
        </html>
    );
}
